apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: grouper-prod
spec:
  imagePullSecrets:
    - name: captain-regcreds
  image: captain.escs.udel.edu:5000/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: "grouper-prod-pgo"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: captain.escs.udel.edu:5000/crunchy-pgbackrest:ubi8-2.38-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: "grouper-prod-repo-pgo"
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
