apiVersion: v1
kind: PersistentVolume
metadata:
    labels:
        app: grouper-prod-pgo
    name: grouper-prod-pgo
    annotations:
        pv.beta.kubernetes.io/gid: "26"

# Make directory uid:gid writable with 26:26.

spec:
    storageClassName: "grouper-prod-pgo"
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 40G
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/k8s_data/grouper-pgo/prod/grouper-0"

    nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - gainful-wh02.escs.udel.edu
