apiVersion: v1
kind: PersistentVolume
metadata:
    labels:
        app: grouper-prod-repo-pgo-pv
    name: grouper-prod-repo-pgo
    annotations:
        pv.beta.kubernetes.io/gid: "26"

spec:
    storageClassName: "grouper-prod-repo-pgo"
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 40G

    nfs:
        path: "/kube-pv/grouper-prod-pgo/"
        server: "gainful-pv01.escs.udel.edu"

    persistentVolumeReclaimPolicy: Retain

