###############################################################################
# kube-pv-iscsi-secret.yml                                                   #
#                                                                            #
# Fraser Gutteridge, blue@udel.edu    2022-02-22                             #
# University of Delaware IT-ESCS Unix Systems Engineering                    #
#                                                                            #
# CHAP auth credentials for the gainful-pv01 iSCSI PV.                       #
##############################################################################

apiVersion: v1
kind: Secret
metadata:
  name: kube-pv-iscsi-secret
  namespace: postgres-operator
type: "kubernetes.io/iscsi-chap"
data:
  # xfoTRLWCglwIRZ1
  node.session.auth.username: eGZvVFJMV0NnbHdJUlox
  # 4NSjGczN5P3m1gR
  node.session.auth.password: NE5Takdjek41UDNtMWdS

